### PR TITLE
linked gui and parser (#18)

### PR DESCRIPTION
**Pull request by Nephty**
Added method in App class that evaluates the user input attribute (this attribute is updated according to the text field in the controller)

Added usage of this method in the controller so that the parser is linked to the GUI.

The new method uses the new read method introduced by the parser and then calls the already existing eval method with that result.

### CODE REVIEW

**Comment by Nephty** [comment]
When this is merged we can probably release 1.0.0.

**Review by VionFrancois — APPROVED** [review]
Great job, I'm so excited about the 1.0.0 release :raised_hands:

**Review by MrRose765 — APPROVED** [review]
Don't forget to add unit test for the input. Otherwise, it's good :+1:

**Comment by VionFrancois** [comment]
With the UI improvements and refactoring, I think we can finally merge to main. Can you check if it's good for you guys ?

**Review by VionFrancois — APPROVED** [review]

**Review by ThomasBernard28 — APPROVED** [review]
Reviewed, tested and ran the branch seems to work

**Review by MrRose765 — APPROVED** [review]
I added a listener to give the possibility to get the result of an expression by pressing enter. Otherwise, LGTM :+1:

**Pull request merged**
