### PR TITLE
introduce logger and back/front structure

### PR DESCRIPTION
**Pull request by Nephty**
Moved packages into the back package. Added a front package that will be used for the GUI (currently being worked on in #14).

The logger allows for logging at any level and getting a report of the logs in both XML and HTML format. The logger is created in the Main class and uses the `LoggerHelper` class which contains all useful features. Log anything using the `Main.logger.log` method.

The logger must be prepared before usage via `LoggerHelper.prepareLogger(<your_logger>)`.

Everytime something is logged, it is saved in an XML log file ending in `.log`. As stated in the class documentation :

> Log files are stored at [user.home]/.logs/calculator-cucumber/. On Unix, [user.home] will be /home/[username].
> On Windows, [user.home] will be [your_disk]\Users\[username], where [your_disk] is the disk where Windows is
> installed. Each log file will be named by their date and time of creation.

When closing the application, a new HTML file is created. This file is a new representation of the logs in a human-readable format. The helper translates the XML content into an HTML table in `transformLogToHTML`.

### CODE REVIEW

**Review by MrRose765 — CHANGES_REQUESTED** [review]
## Tests
I see that the test coverage drops to 58% with in this branch. I don't think that it's caused by the only file that you added but with the modification of the filesystem. We have to solve this before merging.

## Log file localisation ?
I see that the log file is store in the home folder. Wouldn't it be better to save it in the application's folder. (Just my opinion there, maybe it's better in the home folder)

## Future feature
As a next feature, it may be interesting to let the user choose the folder where all the outputs are saved (logs or future outputs)

**Comment by Nephty** [comment]
> ## Tests
> I see that the test coverage drops to 58% with in this branch. I don't think that it's caused by the only file that you added but with the modification of the filesystem. We have to solve this before merging.

I'm not sure how coverage is measured, but I don't see why having more folders would imply have less coverage ? Also, if you have any ideas on how to test a logger, I'd take that.

> ## Log file localisation ?
> I see that the log file is store in the home folder. Wouldn't it be better to save it in the application's folder. (Just my opinion there, maybe it's better in the home folder)

I think that the location of the application's folder can vary greatly from one case to another. If you forget where you installed the application, then you won't be able to find the logs anymore. This has probably happened to us in one way or another : you're not sure where you installed an app and now you're unable to find related files like screenshots or configurations. Having the logs stored at a fixed location provides an easier access to them. Though we could probably think of a better suited location than $HOME/.logs/, for example /tmp/ or $HOME/.local/.

> ## Future feature
> As a next feature, it may be interesting to let the user choose the folder where all the outputs are saved (logs or future outputs)

This relates to the same issue as mentioned above, but I think that if we set a default location and use a settings page to modify it, we might get the good stuff from both ends.

***

Thanks for the feedback

**Comment by MrRose765** [comment]
> > ## Tests 
> I'm not sure how coverage is measured, but I don't see why having more folders would imply have less coverage ? Also, if you have any ideas on how to test a logger, I'd take that.

I thought some tests were skipped because of the modification, but I checked the JaCoCo report, and it's because of the logger file.
image

Isn't it better to use a framework like logback / Log4J ?

**Comment by Nephty** [comment]
> Isn't it better to use a framework like logback / Log4J ? 

This is likely only going to shift the issue. The issue stems from the fact that we are wrapping the logging library with a Helper. We could use the bare library and no longer have the issue but the wrapper is cool for formatting the logs and rendering them as HTML.

Solutions are :

- use one of these library without any wapper (not cool 👎)
- test the code (cool but boring)
- decide that we are not going to test that code (not cool but not boring either)

Plus I spent an entire day witing a clean wrapper :(

**Pull request closed without merging**
