### PR TITLE
Merge stable gui and history manager

### PR DESCRIPTION
**Pull request by Nephty**
Stable GUI :

- Can click on buttons
- Input is shown in the calculator
- Equal buttons does not trigger the parsing & evaluation of the expression but its behavior is separated from the other buttons
- Clear button clears the input
- History manager handles the history of operations : each time an expression is evaluated, it is put in the history of operations using the history manager

Next features to implement :

- Update the display of the history
- Parse the input for evaluation (requires merging with the parser's branch)
- Add a logger

Note :

As for now, the application is not runnable using the jar file. Instead, use `mvn javafx:run`. We are working on fixing this issue.

### CODE REVIEW

**Comment by MrRose765** [comment]
Wouldn't it be useful to add tests for GUI? Apart from that, it looks good to me.

**Comment by VionFrancois** [comment]
The clear button doesn't clear the input for me. Also, don't forget to mention that the program does not work anymore with the .jar file. We need to execute it with mvn javafx:run for the moment. I'm currently working on this issue

**Comment by Nephty** [comment]
> The clear button doesn't clear the input for me. Also, don't forget to mention that the program does not work anymore with the .jar file. We need to execute it with mvn javafx:run for the moment. I'm currently working on this issue

I forgot to add the handler for the clear button, it is now working

**Comment by Nephty** [comment]
Can someone give me their opinion ? @LicorneRose765 @VionFrancois @ThomasBernard28 

If we're on the right track we might pursue the GUI's development

**Review by VionFrancois — APPROVED** [review]
Everything is great for me, can you confirm that the .jar file works for you guys too ?

**Comment by Nephty** [comment]
> Everything is great for me, can you confirm that the .jar file works for you guys too ?
It works on my machine

**Review by Nephty — COMMENTED** [review]
Tried the new configuration with shade and I am now able to run `mvn install` followed by `java -jar <jar_file>` just fine.

**Review by MrRose765 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
